version: "3.8"

# https://docs.docker.com/compose/

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db  # == name of service
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=superpassword123
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superpassword123  # replaced on build server with env var


